baseURL = "https://devdocs.prestashop.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Prestashop Developer Documentation"

theme = "hugo-theme-learn"
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "UA-2753771-44"

[params]
  editURL = "https://github.com/PrestaShop/docs/edit/master/src/content/"
  ghRepoURL = "https://github.com/PrestaShop/docs/"
  ghCommitURL = "https://github.com/PrestaShop/docs/commit/"
  howToContributeURL = "/1.7/documentation/how/"
  description = "Learn how to extend, modify and test PrestaShop, create modules, themes, and more."
  author = "PrestaShop"
  showVisitedLinks = false
  disableInlineCopyToClipBoard = true

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]
