baseURL = "http://devdocs.prestashop.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Prestashop Developer Documentation"

theme = "hugo-theme-learn"
enableGitInfo = true

[params]
  editURL = "https://github.com/PrestaShop/docs/edit/hugo/src/content/"
  ghRepoURL = "https://github.com/PrestaShop/docs/"
  ghCommitURL = "https://github.com/PrestaShop/docs/commit/"
  description = "Prestashop Technical Documentation"
  author = "PrestaShop"
  showVisitedLinks = false
  disableInlineCopyToClipBoard = true

# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]
