baseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Prestashop DevDocs"

theme = "hugo-theme-learn"

[params]
  editURL = "https://github.com/PrestaShop/docs/edit/hugo/src/content/"
  description = "Prestashop Technical Documentation"
  author = "PrestaShop"
  showVisitedLinks = false
  themeVariant = "prestashop"


# For search functionality
[outputs]
  home = [ "HTML", "RSS", "JSON"]
